# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08a76d09976f05185068fa15cdc8a88a5c0e2d32a2b12b5f635c7ae8cf50937d0ee60a9f2d467da8cd0b7122ced1913be21b6e57d2a5fe387afa24fa32865bb3

test:
  secret_key_base: e409e149b7be422e5b3282477d672315c50996b65a0fc56a6a236228d202f6d9dc684a9f3d9bb304fe2cf7d3d67319850a2d913fdc124fd4ce6a4aca1fb98e27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
